from tkinter import *
import NewLivePred

root = Tk()
root.geometry('600x300')

f1 = Frame(root)
f1.grid(row=0, column=0)
l = Label(f1, text="The Brain Boys")
l.grid(row=0, column=0)
b = Button(f1, text="Connect")
b.grid(row=1, column=0, padx=20, pady=10)
b = Button(f1, text="Predict")
b.grid(row=1, column=1)
f2 = Frame(root)
f2.grid(row=2, column=0, pady=20)
l = Label(f2, text="Bot Control")
l.grid(row=0, column=0, pady=5)
b = Button(f2, text="Connect", width=10)
b.grid(row=1, column=0)
b = Button(f2, text="Left", width=10)
b.grid(row=2, column=0)
b = Button(f2, text="Right", width=10)
b.grid(row=3, column=0)
b = Button(f2, text="Backward", width=10)
b.grid(row=4, column=0)
b = Button(f2, text="Forward", width=10)
b.grid(row=5, column=0)
f3 = Frame(root)
f3.grid(row=1, rowspan=5, column=2)
t = Text(f3, height=7, width=40)
t.grid(row=1, column=3)

root.mainloop()